### ISSUE TITLE
Felicidades

### ISSUE THREAD

**Issue by Suizzo** [vaijira/shylock#1]
.Siento escribirte por aquí.
He buscado tu mail o método de contacto por cielo y tierra pero...Vaya proyecto más útil te has marcado con coditia.

**Comment by vaijira** [comment]
Muchas gracias cualquiera mejora que se te ocurra es bienvenida.

**Comment by Suizzo** [comment]
La funcionalidad está genial. El detalle de las oportunidades, todo un
punto.
Participas en las subastas?
Has pensando incluir también las de la seguridad social?
Perdón por preguntar tanto :-)

**Comment by vaijira** [comment]
No he participado todavía en ninguna subasta, se me ocurrió la idea viendo unos videos de Tristán el subastero, el criterio para filtrar por oportunidades lo cogí de él.
Pensaba que las de la seguridad social ya estaban incluidas en subastas.boe.es o que al menos la idea es que las del estado iban a estar centralizadas allí. Mi correo es vaijira en gmail.
